### ISSUE TITLE
Group identical diffs together

### ISSUE THREAD

**Issue by billyvg** [getsentry/action-visual-snapshot#27]
It's possible that a change can affect multiple snapshots in the same way. These should be considered a single "diff" instead of a unique one per snapshot.

We can implement this by diffing the diffs and and making sure that there are no changes between the diffs. This would require us to mask the diffs using a solid color without transparency to be able to ignore the snapshot contents. I believe we currently overlay the diff on top of the original contents.

**Comment by asottile-sentry** [comment]
archiving: closing issues
