### ISSUE TITLE
Turn Github jobs red when something fails

### ISSUE THREAD

**Issue by armenzg** [getsentry/action-visual-snapshot#50]
For instance, [this job](https://github.com/getsentry/sentry/runs/6219855908?check_suite_focus=true#step:3:16) failed yet the job was green.
<img width="785" alt="image" src="https://user-images.githubusercontent.com/44410/165984352-28296be5-4422-49a0-8948-b3a77700339a.png">

**Comment by asottile-sentry** [comment]
archiving: closing issues
